;定义日志系统中使用哪些logger(日志记录器)
[loggers]
keys=root

;配置root logger
[logger_root]
level=INFO
handlers=consoleHandler, fileHandler

;定义使用的日志格式化工具的名称
[formatters]
keys=simpleFormatter

;配置日志格式
[formatter_simpleFormatter]
format=%(asctime)s [%(filename)s:%(lineno)s] [%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S

;定义日志handler
[handlers]
keys=consoleHandler, fileHandler

;配置控制台输出handler
[handler_consoleHandler]
class=StreamHandler
formatter=simpleFormatter

;配置文件输出handler
[handler_fileHandler]
class=FileHandler
formatter=simpleFormatter
args=('../log/wenku.log', 'w', 'utf-8')
